### ISSUE TITLE
Paths with Spaces on macOS do not resolve

### ISSUE THREAD

**Issue by rabrowne85** [higoka/php-cs-fixer#4]
When trying to use this within a path location where a folder has a space in the name, the following error output is generated:

```
In ConfigurationResolver.php line 388:
                                                     
  The path "/Users/name/Folder" is not readable.  
                                                     

fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--diff-format DIFF-FORMAT] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>...]


	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

The true path is actually akin to: `/Users/name/Folder Name/SomeFile.php`

**Comment by higoka** [comment]
Thank you for the issue and also for the pull request!
